users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdj13+bbDlo6OnHidvsB+ehnU9V+FL+NSyn9rVXjaiJucB4rHki7mInIF3ui2PmbHT2fT+WVwrCvD0Hb9i68ZLP4YgggeLqYGAMCOrZV2ZlVlEE9zd5BgGXIXFy9YC5ZCvQbUYVlKbErA3QfEBg9C3FsJGH/OBedOhgBHMRrrxUt3oWHEHqekhB0zIr4W4uKbMOMknd9raS9niS0joTverIsZYiTz27CFTY3/UmjMBOlJc3vIlUn5zogYSFIbPorTGUt3rgyr1r26Z94azBG9UKBWXUZ4W6O4iQSk53ypqpELXIBCOWAmh/hgu/gkUNz6wOZiFSpNlPV3i1NJawt/T jamiraa
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [docker]
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
final_message: "The system is finally up, after $UPTIME seconds"
write_files:
  - path: /home/ubuntu/docker-compose.yml
    content: |
      version: '3'

      services:
        m347-kn04a-web:
          image: jamiraa/m347:kn02b-web
          networks:
            - m347-network
          ports:
            - "80:80"
          container_name: m347-kn04a-web

        m347-kn04a-db:
          image: mariadb:latest
          networks:
            - m347-network
          environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mysql
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
          container_name: m347-kn04a-db

      networks:
        m347-network:
          ipam:
            driver: default
            config:
              - subnet: 172.20.0.0/16
                ip_range: 172.20.5.0/24
                gateway: 172.20.5.254

runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
  - systemctl enable docker
  - systemctl start docker
  - cd /home/ubuntu && docker-compose up -d
