version: '3.8'

services:
  web:
    image: norisgiro/kn02a:latest
    container_name: m347-kn04a-web2
    ports:
      - "8080:80"
    networks:
      m347-kn04a-network:
        ipv4_address: 172.15.5.10

  db:
    image: mariadb:latest
    container_name: m347-kn04a-db2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: noris
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      m347-kn04a-network:
        ipv4_address: 172.15.5.11

networks:
  m347-kn04a-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16
          ip_range: 172.15.5.0/24
          gateway: 172.15.5.254
